#!/bin/bash

echo
echo "#####################################"
echo "#  Docker-Compose NGINX Restarting  #"
echo "#####################################"


echo -e "Restarting Laradock NGINX image"
FILE="docker-compose.yml"    
if [ -f $FILE ]; then
   docker-compose restart nginx
else
   cd .. && docker-compose restart nginx
fi

exit 0