#!/bin/bash

# based from https://gist.github.com/irazasyed/a7b0a079e7727a4315b9 and https://gist.github.com/bzerangue/4393408

SCRIPT_FILENAME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

# PATH TO YOUR HOSTS FILE
ETC_HOSTS=/etc/hosts

# DEFAULT IP FOR HOSTNAME
IP="127.0.0.1"

# Hostname to add/remove.
HOSTNAME=$2

function remove()
{
    if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
    then
        echo -e "$HOSTNAME Found in your $ETC_HOSTS, Removing now...";
        sudo sed -i".bak" "/$HOSTNAME/d" $ETC_HOSTS
    else
        echo -e "$HOSTNAME was not found in your $ETC_HOSTS";
    fi
}

function add()
{
    HOSTS_LINE="$IP\t$HOSTNAME"
    if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
        then
            echo -e "$HOSTNAME already exists : $(grep $HOSTNAME $ETC_HOSTS)"
        else
            echo -e "Adding $HOSTNAME to your $ETC_HOSTS";
            sudo -- sh -c -e "echo -e '$HOSTS_LINE' >> /etc/hosts";

            if [ -n "$(grep $HOSTNAME /etc/hosts)" ]
                then
                    echo -e "$HOSTNAME was added succesfully \n $(grep $HOSTNAME /etc/hosts)";
                else
                    echo -e "Failed to Add $HOSTNAME, Try again!";
            fi
    fi
}

echo
echo "#################################"
echo "#  Hosts Configuration Manager  #"
echo "#################################"

case "$1" in
    -a|--add|add)
        echo -e "- Adding New Entry in $ETC_HOSTS \n"
        add
        ;;
    -r|--remove|remove)
        echo -e "- Removing Entry in $ETC_HOSTS \n"
        remove
        ;;

    *)
        echo "Usage: "
        echo -e "$SCRIPT_FILENAME [-a|--add|add] [hostname] [ip]"
        echo -e "$SCRIPT_FILENAME [-r|--remove|remove] [hostname] [ip]"
        echo 
        echo "Ip defaults to 127.0.0.1"
        echo "Examples:"
        echo -e "$SCRIPT_FILENAME add project.dev"
        echo -e "$SCRIPT_FILENAME remove project.dev"
        exit 1
        ;;
esac

exit 0