#!/bin/bash

echo
echo "#####################################"
echo "#  Docker-Compose NGINX Restarting  #"
echo "#####################################"


echo -e "Restarting Laradock NGINX image"
docker-compose restart nginx